### ISSUE TITLE
Issue with customvalidators generation

### ISSUE THREAD

**Issue by amondacaSN** [sngular/scs-multiapi-plugin#277]
I have found an issue when I have used the async-api code generation function. When you configure different modelPackages for supplier and consumer, and the async-api spec has restrictions like required fields, the plugin do not generate the code propertly having several compilation errors.

This errors happen because the model classes (allocated in different packages for supplier and cosumer) try to reference customvalidators in his same package hierarchy, but this validators are only generated in one of them.

**Comment by joseegman** [comment]
Hi @amondacaSN — on current `main`, when the consumer and supplier use different `modelPackage`s and reference the same constrained schema, the `customvalidator` folder (annotations + validators) is generated in **both** packages and each model imports them from its own package. This was fixed by later refactors.

Added a regression test (`testCustomValidatorsDifferentPackages`, in PR #411) that reproduces this configuration and asserts the validators are generated in both consumer and producer packages.
